# Generated by Django 4.2.1 on 2023-06-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='lasta_name',
            new_name='last_name',
        ),
    ]
